/** S3 Foundations quiz — Topics in worksheet settings are F01 and F02. */
export const QUIZ_SECTIONS = [
  { id: "quantities-units", label: "F01 Quantities and Units", labelZh: "F01 物理量與單位" },
  { id: "useful-maths", label: "F02 Useful Mathematics in Physics", labelZh: "F02 物理中常用的數學" },
];

export const QUIZ_ITEMS = [
  {
    id: "qu-q01",
    section: "quantities-units",
    difficulty: "Foundation",
    stem: "What is the base SI unit of length?",
    options: [
      { key: "A", text: "m" },
      { key: "B", text: "metre" },
      { key: "C", text: "kilometre" },
      { key: "D", text: "centimetre" },
    ],
    answer: "B",
    hint: "The base SI unit is metre. m is only the symbol for that unit.",
  },
  {
    id: "qu-q02",
    section: "quantities-units",
    difficulty: "Foundation",
    stem: "What is the symbol for the base SI unit of mass?",
    options: [
      { key: "A", text: "kilogram" },
      { key: "B", text: "kg" },
      { key: "C", text: "g" },
      { key: "D", text: "m" },
    ],
    answer: "B",
    hint: "kg is the symbol. kilogram is the name of the unit.",
  },
  {
    id: "qu-q03",
    section: "quantities-units",
    difficulty: "Foundation",
    stem: "Write 4600 in scientific notation (1 figure before the decimal point).",
    options: [
      { key: "A", text: "4.6 × 10²" },
      { key: "B", text: "4.6 × 10³" },
      { key: "C", text: "46 × 10²" },
      { key: "D", text: "4.6 × 10⁻³" },
    ],
    answer: "B",
    hint: "Move the decimal point so there is one figure before it: 4.6 × 10³.",
  },
  {
    id: "qu-q04",
    section: "quantities-units",
    difficulty: "Foundation",
    stem: "Which is the most suitable prefix form of 0.007 s?",
    options: [
      { key: "A", text: "7 ms" },
      { key: "B", text: "7 μs" },
      { key: "C", text: "7 ks" },
      { key: "D", text: "0.7 cs" },
    ],
    answer: "A",
    hint: "milli (m) means 10⁻³, so 0.007 s = 7 ms.",
  },
  {
    id: "qu-q05",
    section: "quantities-units",
    difficulty: "Foundation",
    stem: "Convert 36 km/h to m/s.",
    options: [
      { key: "A", text: "6" },
      { key: "B", text: "10" },
      { key: "C", text: "36" },
      { key: "D", text: "129.6" },
    ],
    answer: "B",
    hint: "36 × (1000 m) / (3600 s) = 36 × 5/18 = 10 m/s.",
  },
  {
    id: "um-q01",
    section: "useful-maths",
    difficulty: "Foundation",
    stem: "A straight line passes through (0, 4) and (3, 0). What is the y-intercept?",
    options: [
      { key: "A", text: "3" },
      { key: "B", text: "−4/3" },
      { key: "C", text: "4" },
      { key: "D", text: "0" },
    ],
    answer: "C",
    hint: "The y-intercept is where the line meets the y-axis (x = 0), so b = 4. 3 is the x-intercept; −4/3 is the slope.",
  },
  {
    id: "um-q02",
    section: "useful-maths",
    difficulty: "Foundation",
    stem: "Line AB passes through A(−3, 4) and B(−1, 1). What is the slope m_AB?",
    options: [
      { key: "A", text: "−3/2" },
      { key: "B", text: "3/2" },
      { key: "C", text: "−3/4" },
      { key: "D", text: "2/3" },
    ],
    answer: "A",
    hint: "m = (y₂ − y₁) / (x₂ − x₁) = (1 − 4) / ((−1) − (−3)) = −3/2.",
  },
  {
    id: "um-q03",
    section: "useful-maths",
    difficulty: "Foundation",
    stem: "A straight line passes through (0, 1) and (6, 4). Its equation is",
    options: [
      { key: "A", text: "y = 2x + 1" },
      { key: "B", text: "y = (1/2)x + 4" },
      { key: "C", text: "y = x + 1" },
      { key: "D", text: "y = (1/2)x + 1" },
    ],
    answer: "D",
    hint: "The line meets the y-axis at 1. Slope = (4 − 1)/(6 − 0) = 1/2, so y = (1/2)x + 1.",
  },
  {
    id: "um-q04",
    section: "useful-maths",
    difficulty: "Foundation",
    stem: "For y = 3x − 1, the slope and y-intercept are",
    options: [
      { key: "A", text: "−1 and 3" },
      { key: "B", text: "3 and −1" },
      { key: "C", text: "3 and 1" },
      { key: "D", text: "−3 and −1" },
    ],
    answer: "B",
    hint: "In y = mx + b, m is the slope and b is the y-intercept, so m = 3 and b = −1.",
  },
  {
    id: "um-q05",
    section: "useful-maths",
    difficulty: "Foundation",
    stem: "Rewrite 8x − 5y + 40 = 0 as y = mx + b.",
    options: [
      { key: "A", text: "y = (5/8)x + 8" },
      { key: "B", text: "y = (8/5)x − 8" },
      { key: "C", text: "y = (8/5)x + 8" },
      { key: "D", text: "y = −(8/5)x + 8" },
    ],
    answer: "C",
    hint: "5y = 8x + 40, so y = (8/5)x + 8.",
  },
];
